## 1. AND Gate : 

In [1]:
import numpy as np
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [2]:
def AND(lr,number_of_iter = 100):
    x = np.array([[0,0],[0,1],[1,0],[1,1]]).T # all possible values of x
    y = np.array([[0],[0],[0],[1]]).T
    m = len(y[0])
    w = np.zeros((x.shape[0],1))
    b = 0
    for i in range(number_of_iter+1) :
        z = np.dot(w.T,x) + b 
        h_theta = sigmoid(z)
        cost = (-1/m) * np.sum( y*np.log(h_theta) + (1-y)*np.log(1-h_theta) )
        dz =  (h_theta-y)
        dw = (1/m) * np.dot(x,dz.T)
        db = (1/m) * np.sum(dz)
        w = w - lr*dw
        b = b - lr*db
        if i % 10 == 0 :
            print('cost after',i,'th iteration:',cost)
    return w,b

In [3]:
w,b = AND(80)

cost after 0 th iteration: 0.6931471805599453
cost after 10 th iteration: 3.398826362959129e-05
cost after 20 th iteration: 3.389091071982835e-05
cost after 30 th iteration: 3.3798325518402846e-05
cost after 40 th iteration: 3.371003070295256e-05
cost after 50 th iteration: 3.3625598267325455e-05
cost after 60 th iteration: 3.354464441281246e-05
cost after 70 th iteration: 3.346682497461511e-05
cost after 80 th iteration: 3.3391831325921194e-05
cost after 90 th iteration: 3.331938670681965e-05
cost after 100 th iteration: 3.3249242934473854e-05


C:\Users\shaur\anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in log
  # Remove the CWD from sys.path while we load stuff.
C:\Users\shaur\anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in multiply
  # Remove the CWD from sys.path while we load stuff.


In [4]:
print(w,b)

[[20.00649809]
 [20.00649809]] -30.078303748769954


## 2. OR Gate 

In [5]:
def OR(lr,number_of_iter = 100):
    x = np.array([[0,0],[0,1],[1,0],[1,1]]).T # all possible values of x
    y = np.array([[0],[1],[1],[1]]).T
    m = len(y[0])
    w = np.zeros((x.shape[0],1))
    b = 0
    for i in range(number_of_iter+1) :
        z = np.dot(w.T,x) + b 
        h_theta = sigmoid(z)
        cost = (-1/m) * np.sum( y*np.log(h_theta) + (1-y)*np.log(1-h_theta) )
        dz =  (h_theta-y)
        dw = (1/m) * np.dot(x,dz.T)
        db = (1/m) * np.sum(dz)
        w = w - lr*dw
        b = b - lr*db
        if i % 10 == 0 :
            print('cost after',i,'th iteration:',cost)
    return w,b

In [6]:
w,b = OR(80)

cost after 0 th iteration: 0.6931471805599453
cost after 10 th iteration: 3.383654099589471e-05
cost after 20 th iteration: 3.354624793580835e-05
cost after 30 th iteration: 3.327069966676072e-05
cost after 40 th iteration: 3.300877640550772e-05
cost after 50 th iteration: 3.275945912975126e-05
cost after 60 th iteration: 3.25218189851724e-05
cost after 70 th iteration: 3.229500798359724e-05
cost after 80 th iteration: 3.207825081210812e-05
cost after 90 th iteration: 3.1870837601727585e-05
cost after 100 th iteration: 3.167211752834262e-05


C:\Users\shaur\anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in log
  # Remove the CWD from sys.path while we load stuff.
C:\Users\shaur\anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in multiply
  # Remove the CWD from sys.path while we load stuff.


In [7]:
print(w,b)

[[20.08221824]
 [20.08221824]] -9.92803564092803


## 3. NOT Gate

In [8]:
def NOT(lr,number_of_iter = 100):
    x = np.array([[0],[1]]).T # all possible values of x
    y = np.array([[1],[0]]).T
    m = len(y[0])
    w = np.zeros((x.shape[0],1))
    b = 0
    for i in range(number_of_iter+1) :
        z = np.dot(w.T,x) + b 
        h_theta = sigmoid(z)
        cost = (-1/m) * np.sum( y*np.log(h_theta) + (1-y)*np.log(1-h_theta) )
        dz =  (h_theta-y)
        dw = (1/m) * np.dot(x,dz.T)
        db = (1/m) * np.sum(dz)
        w = w - lr*dw
        b = b - lr*db
        if i % 10 == 0 :
            print('cost after',i,'th iteration:',cost)
    return w,b

In [9]:
w,b = NOT(44)

cost after 0 th iteration: 0.6931471805599453
cost after 10 th iteration: 1.6716639700418993e-05
cost after 20 th iteration: 1.6687016561867693e-05
cost after 30 th iteration: 1.6657590050576013e-05
cost after 40 th iteration: 1.6628356814733112e-05
cost after 50 th iteration: 1.6599313584965193e-05
cost after 60 th iteration: 1.6570457171559817e-05
cost after 70 th iteration: 1.6541784462633974e-05
cost after 80 th iteration: 1.651329242169148e-05
cost after 90 th iteration: 1.648497808540246e-05
cost after 100 th iteration: 1.6456838561382794e-05


In [10]:
print(w,b)

[[-22.03088187]] 10.983522924950247


## 4. XNOR Gate

In [36]:
def XNOR(lr,number_of_iter = 100):
    x = np.array([[0,0],[0,1],[1,0],[1,1]]).T # all possible values of x
    y = np.array([[1],[0],[0],[1]]).T         # and their outputs
    m = len(y[0])
    w1 = np.random.rand(x.shape[0],2)*0.01 # I layer: 2 neurons 
    w2 = np.random.rand(x.shape[0],1)*0.01 # II layer: 1 neuron
    b1 = np.zeros((x.shape[0],1))
    b2 = 0
    for i in range(number_of_iter+1) :
        z1 = np.dot(w1.T,x) + b1 # first layer computation
        h_theta1 = sigmoid(z1)
        z2 = np.dot(w2.T,h_theta1) + b2 # second layer computation
        h_theta2 = sigmoid(z2)
        cost = (-1/m) * np.sum(y*np.log(h_theta2) + (1-y)*np.log(1-h_theta2))
        
        dz =  (h_theta2-y)
        
        dw2 = (1/m) * np.dot(h_theta1,dz.T)
        db2 = (1/m) * np.sum(dz)
        
        dz_ = np.dot(w2,dz) * np.multiply(h_theta1,(1-h_theta1))
        
        dw1 = (1/m) * np.dot(x,dz_.T)
        db1 = (1/m) * np.sum(dz_,axis = 1 , keepdims = True)
        
        w2 = w2 - lr*dw2
        b2 = b2 - lr*db2
        w1 = w1 - lr*dw1.T
        b1 = b1 - lr*db1
        if i % 10000 == 0 :
            print('cost after',i,'th iteration:',cost)

    print(dw1.shape,dw2.shape)
    return w1,b1,w2,b2

In [38]:
w1,b1,w2,b2 = XNOR(0.01,100000)

cost after 0 th iteration: 0.6931537704152507
cost after 1000 th iteration: 0.6931471841345792
cost after 2000 th iteration: 0.6931471805784164
cost after 3000 th iteration: 0.6931471805764958
cost after 4000 th iteration: 0.6931471805764945
cost after 5000 th iteration: 0.6931471805764938
cost after 6000 th iteration: 0.6931471805764935
cost after 7000 th iteration: 0.6931471805764929
cost after 8000 th iteration: 0.6931471805764924
cost after 9000 th iteration: 0.693147180576492
cost after 10000 th iteration: 0.6931471805764914
cost after 11000 th iteration: 0.6931471805764909
cost after 12000 th iteration: 0.6931471805764904
cost after 13000 th iteration: 0.6931471805764899
cost after 14000 th iteration: 0.6931471805764895
cost after 15000 th iteration: 0.693147180576489
cost after 16000 th iteration: 0.6931471805764884
cost after 17000 th iteration: 0.6931471805764879
cost after 18000 th iteration: 0.6931471805764875
cost after 19000 th iteration: 0.693147180576487
cost after 20000

In [27]:
 print(w1,b1,w2,b2)

[[-11.77482544 -11.70388905]
 [-11.77482543 -11.70388909]] [[0.72281399]
 [0.67010554]] [[8.029815  ]
 [7.86092036]] -0.6932423854228871


In [140]:
print(a)

[[0.42099792 0.02803407]
 [0.10815632 0.22080518]]
